### ISSUE TITLE
Running the code cleaner

### ISSUE THREAD

**Issue by Fonotec** [Fonotec/PSF#3]
Currently the code needs to be run with additional arguments that means that running the program can be a bit confusing. 

I propose that we make a standard parameter file that is read by the program instead of using a complicated terminal command to do the same. This makes is easier for us and other users like from CAMRAS to use our code.

**Comment by Fonotec** [comment]
Okay, I started making a param.yml file for the input parameters. More parameters can be added to this file, I also constructed a class to read the param.yml file and to use it easily in the code. See the merge request.

**Comment by ewoudw** [comment]
I adjusted it already a bit, and am currently adapting the code to use it. I will probably drop support for running it the old way (so arguments to specify data file, nbins etc. will no longer be accepted), as that makes the code cleaner. Agreed?

**Comment by ewoudw** [comment]
Also, I'll probably adjust the param file syntax a bit, so it'd be best to wait a bit making examples until that is clear.

**Comment by Fonotec** [comment]
Agreed, that way running the code is cleaner. The changes so far look good, I will put making the examples on hold.

**Comment by ewoudw** [comment]
Everything works with the new yml files now that #7 is merged. (except the chi squared fitting parameters, see #9)
